### ISSUE TITLE
Codice non commentato

### ISSUE THREAD

**Issue by ghost** [algomera/cliplaza#1]
Come da oggetto, il codice non è commentato.

**Comment by massimolunetta** [comment]
Ciao Alessio, ho pushato le modifiche per le altre issues, al prossimo commit troverai più commenti sul codice. Le altre 2 issues puoi eliminarle tu o le assegni anche a questo profilo cosi posso chiuderle io, grazie.

**Comment by ghost** [comment]
Ciao Massimo,
ci sei solo in una delle tre Issues!
